### ISSUE TITLE
Errors when installing

### ISSUE THREAD

**Issue by umesh-onshape** [albertusk95/weight-of-evidence-spark#1]
Hi Greetings!

I see these errors when I try to install this on AWS EMR master node:

```
weight-of-evidence-spark-master]$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing weight_of_evidence_information_value.egg-info/PKG-INFO
writing top-level names to weight_of_evidence_information_value.egg-info/top_level.txt
writing dependency_links to weight_of_evidence_information_value.egg-info/dependency_links.txt
reading manifest file 'weight_of_evidence_information_value.egg-info/SOURCES.txt'
writing manifest file 'weight_of_evidence_information_value.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
byte-compiling build/bdist.linux-x86_64/egg/woe_iv/woe.py to woe.pyc
  File "build/bdist.linux-x86_64/egg/woe_iv/woe.py", line 8
    def __init__(self, df: DataFrame, cols_to_woe: [str], label_column: str, good_label: str):
                         ^
SyntaxError: invalid syntax

copying weight_of_evidence_information_value.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying weight_of_evidence_information_value.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying weight_of_evidence_information_value.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying weight_of_evidence_information_value.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    packages=find_packages())
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 218, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 269, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 379, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 416, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by umesh-onshape** [comment]
The above was resolved if done fresh, probably a python version issue.
